Update efd_model-validation.ru.md
Flexberry/flexberry.github.io pull request #111
Opened 2020-09-04 06:34 UTC by DubrovinPavel

2020-09-04 06:46 UTC, bratchikov requested changes

2020-09-04 06:46 UTC, bratchikov commented on pages/products/flexberry-ember/work-with-data/efd_model-validation.ru.md
> +## Аддон ember-cp-validations
Укажи в первом абзаце, что этот аддон используется в проектах на ember-flexberry 3.*

2020-09-04 06:46 UTC, bratchikov commented on pages/products/flexberry-ember/work-with-data/efd_model-validation.ru.md
> +## Аддон Ember Validations
Укажи в первом абзаце, что этот аддон используется в проектах на ember-flexberry 2.*

2020-09-04 06:46 UTC, bratchikov commented on pages/products/flexberry-ember/work-with-data/efd_model-validation.ru.md
> +  имяСвойства: {
Лучше использовать латинские названия. Тем более, что у нас есть автопереводчик.

2020-09-04 06:46 UTC, bratchikov commented on pages/products/flexberry-ember/work-with-data/efd_model-validation.ru.md
> +      validator(валидатор),
Тут тоже лучше латинские и в следующий строке.

2020-09-04 06:46 UTC, bratchikov commented on pages/products/flexberry-ember/work-with-data/efd_model-validation.ru.md
> +	  validator(валидатор2),
Я не понял что такое валидатор2, откуда его брать и почему 2?

2020-09-04 06:49 UTC, DubrovinPavel commented on pages/products/flexberry-ember/work-with-data/efd_model-validation.ru.md
> +	  validator(валидатор2),
ну возможно тут стоит не в общем виде тогда написать, а чисто конкретный пример

2020-09-04 10:06 UTC, bratchikov approved these changes

2020-09-07 12:47 UTC, Nasutya commented on pages/products/flexberry-ember/work-with-data/efd_model-validation.ru.md
>  Прикладные разработчики также могут создавать свои кастомные валидаторы, если имеющихся валидаторов не достаточно для реализации прикладной логики.
"Вылидаторов" во втором случае можно опустить.

2020-09-07 12:47 UTC, Nasutya commented on pages/products/flexberry-ember/work-with-data/efd_model-validation.ru.md
"Здесь" лучше заменить на "в описании валидаторов на GitHub".

2020-09-07 12:47 UTC, Nasutya commented on pages/products/flexberry-ember/work-with-data/efd_model-validation.ru.md
> +```javascript
Пустую строчку лучше добавить после "Например"

2020-09-21 06:20 UTC, KollegOFF commented on pages/products/flexberry-ember/work-with-data/efd_model-validation.ru.md
> +Для `hasMany` связи: `validator('has-many')`.
Здесь может подробней расписать что и для чего генерируется?

2020-09-21 06:20 UTC, KollegOFF commented on pages/products/flexberry-ember/work-with-data/efd_model-validation.ru.md
> +```
Давай в примерах не будем так показывать, лучше через `jQuery.extend` или `{ ...validationRules }` это делать, чтобы не изменять генерируемый объект.

2020-09-21 21:30 UTC, merged