Some grammar fixes
Flexberry/flexberry.github.io pull request #116
Opened 2020-09-22 09:22 UTC by Anisimova2020

Just some grammar fixes

2020-09-22 12:15 UTC, ehaberev requested changes

2020-09-22 12:15 UTC, ehaberev commented on pages/guides/practical-guides/flexberry-ember/gpg_ember-flexberry-components.md
> +Как мы видим, используемый компонент календаря по умолчанию позволяет выбрать только дату, без времени. В нашем приложении необходимо помимо даты выбрать также и время. Перейдем к **шаблону** соответ
Ссылку надо поправить на
ef2_edit-form-components.html

2020-09-23 09:28 UTC, Anisimova2020 commented on pages/guides/practical-guides/flexberry-ember/gpg_ember-flexberry-components.md
> +Как мы видим, используемый компонент календаря по умолчанию позволяет выбрать только дату, без времени. В нашем приложении необходимо помимо даты выбрать также и время. Перейдем к **шаблону** соответ
Fixed

2020-09-23 09:53 UTC, ehaberev approved these changes

2020-09-23 10:21 UTC, merged