Add bottomPaginationn documentation
Flexberry/flexberry.github.io pull request #120
Opened 2020-10-05 10:12 UTC by PashaMasalkin

2020-10-05 13:38 UTC, ehaberev requested changes

2020-10-05 13:38 UTC, ehaberev commented on pages/products/flexberry-ember/2.x/components/ef2_object-list-view.ru.md
> +colsConfigButton: true
Кажется, тут не хватает запятых.

2022-12-29 03:31 UTC, turbcool commented
Закрыть вместе с ПР https://github.com/Flexberry/ember-flexberry/pull/1216

2022-12-29 03:32 UTC, turbcool commented on pages/products/flexberry-ember/2.x/components/ef2_object-list-view.en.md
> +`bottomPaginationn`| Flag that determines whether to display pagination bottom/up.
`bottomPagination` - с одной n

2022-12-29 03:33 UTC, turbcool commented on pages/products/flexberry-ember/2.x/components/ef2_object-list-view.en.md
> +bottomPaginationn: true
`bottomPagination` - с одной n

2022-12-29 03:33 UTC, turbcool commented on pages/products/flexberry-ember/2.x/components/ef2_object-list-view.ru.md
> +`bottomPaginationn`| Флаг, определяющий положение пагинации верху/снизу.
`bottomPagination` - с одной n

2023-12-05 12:06 UTC, closed without merging