Liquibase section ru
Flexberry/flexberry.github.io pull request #168
Opened 2023-05-29 11:18 UTC by torres6093

2023-05-29 11:28 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +**`Liquibase`** - независимая от базы данных библиотека с открытым исходным кодом для отслеживания, управления и применения изменений схемы базы данных.
Отсюда можно сделать ссылку на официальный сайт.

2023-05-29 11:29 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +В качестве примера рассматривается генерация для `PostgreSQL`.
Не совсем понятно, что имеется в виду.

2023-05-29 11:32 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Для того, чтобы сгенерировать SQL для liquibase в оффлайн версии дизайнера, необходимо нажать правой кнопкой мыши на стадию и перейти по следующему пути:
"SQL для liquibase" - может до этого  пояснить, что дизайнер может генерировать SQL для liquibase, он нужен для того-то. А то так не совсем понятно.

2023-05-29 11:34 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Для того, чтобы сгенерировать SQL для liquibase в онлайн версии дизайнера, необходимо, чтобы в файле `GenConfig.fdg` было указано `"LiquibaseSQL": true` в соответствующем разделе:
Аналогично, может так и называть веб-версией. Можно сразу ссылку на сайт с дизайнером.

2023-05-29 11:35 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Для того, чтобы сгенерировать SQL для liquibase в онлайн версии дизайнера, необходимо, чтобы в файле `GenConfig.fdg` было указано `"LiquibaseSQL": true` в соответствующем разделе:
"чтобы в файле `GenConfig.fdg`" - нужно либо ссылку на другую страницу подобрать, либо кратко пояснить, откуда файл этот брать.

2023-05-29 11:36 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Для того, чтобы сгенерировать SQL для liquibase в онлайн версии дизайнера, необходимо, чтобы в файле `GenConfig.fdg` было указано `"LiquibaseSQL": true` в соответствующем разделе:
"`"LiquibaseSQL": true`" - мне кажется, что нужно прямо прописать, что этой настройки может не быть и её ручками нужно добавить и расписать, куда именно.

2023-05-29 11:37 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +- Также не стоит забывать о том, что в веб версии дизайнера можно получить изменения, генерируя код лишь для выбранных классов, а не для всей стадии целиком.
Не совсем понятно, какая практическая польза от данного примечания. Причём тут ликвибейз?

2023-05-29 11:39 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Для описания изменений предназначен файл `changelog.xml`. Помимо описания изменений файл содержит метаданные, а именно:
Нужен какой-то дополнительный контекст, что это за файл и для чего.

2023-05-29 11:44 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Для обновления базы данных можно воспользоваться командой:
Где именно нужно выполнять эту команду? Должно ли стоять какое-то ПО для этого?

2023-05-29 11:47 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +<div class="panel-group">
Этот шаблон откуда-то скопирован?

2023-05-29 12:44 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +**`Liquibase`** - независимая от базы данных библиотека с открытым исходным кодом для отслеживания, управления и применения изменений схемы базы данных.
1. Согласна про ссылку на сайт. Она нужна.
2. В тексте крайне нежелательно использовать личностные местоимения (мы, наш, наше и тп), все строго обезличено. В данном случае, `Liquibase`, поддерживаемой технологией... [название технологии]
3. Со слова "например" лучше отдельным приложением и использовать более "официальные" названия (если есть)
4. **`Liquibase`** - ** лишние, кажется

2023-05-29 12:44 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +В качестве примера рассматривается генерация для `PostgreSQL`.
Да, лучше уточнить, в качестве примера чего (для чего и почему - кратко)

2023-05-29 12:44 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Для того, чтобы сгенерировать SQL для liquibase в оффлайн версии дизайнера, необходимо нажать правой кнопкой мыши на стадию и перейти по следующему пути:
1. Flexberry Designer (и дать ссылку на статью)
2. Здесь и далее "для того чтобы". Запятая не нужна

2023-05-29 12:44 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Для того, чтобы сгенерировать SQL для liquibase в онлайн версии дизайнера, необходимо, чтобы в файле `GenConfig.fdg` было указано `"LiquibaseSQL": true` в соответствующем разделе:
Аналогично примечанию выше.

2023-05-29 12:44 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Для того, чтобы сгенерировать SQL для liquibase в онлайн версии дизайнера, необходимо, чтобы в файле `GenConfig.fdg` было указано `"LiquibaseSQL": true` в соответствующем разделе:
Данная настройка может отсутствовать. В таком случае ее нужно добавить вручную (и далее в соответствии с примечанием Татьяны).

2023-05-29 12:44 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +- Также не стоит забывать о том, что в веб версии дизайнера можно получить изменения, генерируя код лишь для выбранных классов, а не для всей стадии целиком.
Не очень корректно использовать "Также не стоит забывать о том" - "важно обратить внимание", "Внимание:" и т.п.

2023-05-29 12:44 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Для описания изменений предназначен файл `changelog.xml`. Помимо описания изменений файл содержит метаданные, а именно:
Согласна. Так будет более структурировано.

2023-05-29 12:44 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Для обновления базы данных можно воспользоваться командой:
После названий пунктов - пустая строка

2023-05-30 05:57 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Технология поддерживает генерацию SQL-скриптов для таких СУБД, как `PostgreSQL`, `Microsoft SQL Server`, `Oracle`, `Clickhouse`, `Microsoft Access`. В качестве примера ниже рассматривается генерация
У нас точно liquibase и для `Microsoft Access` заработает?

2023-05-30 06:09 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Для описания изменений предназначен файл `changelog.xml`. В нём содержится информация о входящих в обновление наборах изменений (`changesets`). Помимо описания изменений файл содержит метаданные, а и
Мне кажется, что тут нужна минимальная вводная по liquibase. Буквально пару предложений (не нужно детально), чтобы было понятно, что за изменения, откуда файл `changelog.xml`, что за `changesets`. Тогда вероятно будет понятнее, о чём речь.

2023-05-30 06:19 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Для обновления схемы базы данных можно воспользоваться командой, выполнив её в терминале:
Стоит сразу указать, нужно ли какое-то ПО быть установлено, чтобы выполнить.

2023-05-30 21:08 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Для обновления схемы базы данных можно воспользоваться командой, выполнив её в терминале:
После заголовков нужно оставлять пустую строку.

2023-06-01 05:50 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +В данный поддерживается генерация SQL-скриптов под работу с liquibase для СУБД `PostgreSQL` и `Microsoft SQL Server`. В качестве примера ниже рассматривается генерация для `PostgreSQL`.
В данный?

2023-06-01 05:53 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +- Если необходимо обновить несколько схем сразу, то для каждой из них необходимо выполнить аналогичную команду. Можно объединить команды для разных схем в единый .sh файл. Например, синтаксис для вып
"в треминале" => "в терминале"

2023-06-06 06:33 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +- **`ORM -> SQL -> PostgreSQL -> Сгенерировать SQL для liquibase`**
** надо убрать, они не несут практической пользы.

2023-06-06 06:33 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +В разделе **Генерация** главного меню можно указать настройки для генерации приложения, в том числе и настройки генерации для хранилищ данных.
Аналогично. Либо поправить в коде.

2023-06-06 06:33 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +- Для генерации файла с SQL-скриптами в веб версии дизайнера, необходимо для нужного типа хранилища выбрать пункт **"Сгенерировать SQL для liquibase"**
И здесь.

2023-06-06 06:33 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +1) Если изменений немного, то SQL-скрипт можно поместить прямо внутри данного файла:
Нужна пустая строка перед примером кода.

2023-06-06 06:33 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +2) Если SQL-скрипт имеет значительный объём, то выгоднее вынести его в отдельный файл, зафиксировав путь до него:
Аналогично здесь.

2023-06-06 06:33 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +3) Альтернативный вариант - указать директорию, в которой будут храниться все SQL-скрипты:
И здесь.

2023-06-06 06:33 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Для обновления схемы базы данных нужно убедиться, что установлен сам [liquibase](https://docs.liquibase.com/start/install/home.html), а затем воспользоваться командой, выполнив её в терминале:
И здесь

2023-06-06 06:33 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +```
Нужна пустая строка после примера кода.

2023-06-06 06:34 UTC, Nasutya requested changes
Небольшие замечания по стилистике оформления.

2023-06-14 08:28 UTC, Nasutya approved these changes

2023-06-14 09:48 UTC, merged