Added gpg_unique-attributes-validator.md
Flexberry/flexberry.github.io pull request #178
Opened 2023-07-10 04:03 UTC by VChurekov

Валидатор уникальности по нескольким полям для Ember 3.

2023-07-11 12:09 UTC, torres6093 commented on pages/guides/practical-guides/flexberry-ember/gpg_unique-attributes-validator.md
> +- **secondProperty**: Дополнительное свойство для проекрки уникальности;
Опечатка

2023-07-11 12:10 UTC, torres6093 commented on pages/guides/practical-guides/flexberry-ember/gpg_unique-attributes-validator.md
> +Если не указывать атрибут `modelName`, то он автоматически установиться в имя модели текущего проверяемого объекта.
"установится" - без 'ь'

2023-07-11 12:12 UTC, torres6093 commented on pages/guides/practical-guides/flexberry-ember/gpg_unique-attributes-validator.md
> +Когда поменяем текст или дату в нашем примере, на те что нет в хранилище данных, то сообщение валидации исчезает:
Не нужна запятая перед "на", а нужна перед "что" ("Когда поменяем текст или дату в нашем примере на те, что нет в хранилище данных, то сообщение валидации исчезает:")

2023-07-11 12:13 UTC, torres6093 commented on pages/guides/practical-guides/flexberry-ember/gpg_unique-attributes-validator.md
> +Вот почему для работы этого валидатора не тредуется дополнительных доработок со сторны бекенда.
Опечатка "тредуется"

2023-07-14 05:14 UTC, torres6093 approved these changes

2023-07-14 05:35 UTC, AntonIV8 requested changes

2023-07-14 05:35 UTC, AntonIV8 commented on pages/guides/practical-guides/flexberry-ember/gpg_unique-attributes-validator.md
> +- **modelName**: Имя модели, в которой будут проверятся атрибуты;
Вроде в проверятся нужен ь

2023-07-14 05:41 UTC, TeterinaSvetlana approved these changes

2023-07-14 06:34 UTC, AntonIV8 approved these changes

2023-07-14 06:43 UTC, pepelyaeva approved these changes

2023-07-14 06:44 UTC, merged