Дополнена инструкция по Liquibase
Flexberry/flexberry.github.io pull request #184
Opened 2023-07-25 11:23 UTC by turbcool

2023-07-26 06:51 UTC, AntonIV8 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Liquibase позволяет запускать команды через свой CLI. В качестве альтернативы, можно запускать CLI в виде Docker контейнера (не рекомендуется если у вас Windows).
А почему не рекомендуется ? Ведь вроде мы везде его как доке-контейнер используем

2023-07-26 06:54 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Liquibase позволяет запускать команды через свой CLI. В качестве альтернативы, можно запускать CLI в виде Docker контейнера (не рекомендуется если у вас Windows).
У меня были проблемы при передаче путей в контейнер, при запуске команд через Git Bash. Всё-таки, это проблема была с Git Bash, уберу эту пометку.

2023-07-27 08:29 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> -Большинство приложений разрабатывается командой из нескольких человек и имеет несколько стендов. Например, стенд разработки, пре-прод и прод. В связи с этим встаёт вопрос о безопасной и бесконфликтно
Очень нравится этот абзац. может оставим?

2023-07-27 08:34 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +  - Нажите `"Скачать fdg файл"`. Данный файл будет иметь название `GenConfig.fdg`, в нём появится опция `"LiquibaseSQL": true` в разделе, который соответствует выбранной СУБД (в данном примере - `Pos
Если что, то в слове "НажМите" опечатка.
Предлагаю взять оригинальный текст из данной статьи про генерацию из Flexberry Designer и придерживаться его стилистики.

2023-07-27 08:37 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
Предлагаю взять исходную версию этого файла и её расширить, соблюдая стилистику.
Часть информации, которая тут была, новой версией просто перетёрлась.
Если что-то в старой версии было написано принципиально неправильно - то это, думаю, стоит обсудить.

2023-07-27 08:38 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +Чтобы запускать команды Liquibase в Azure Pipelines, необходимо иметь агента сборки с установленным Liquibase CLI. Если такого агента у вас нет, есть альтернативное решение. В момент сборки скрипты н
Мне кажется, что уместна ссылка на страницу с "Liquibase CLI", где его либо взять можно, либо на публичную инструкцию, что это и как работает, где берётся.

2023-07-27 08:47 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +```yaml
Мне кажется, что стоит сделать отдельным примечанием-предупреждением, где именно можно сделать ошибку, что выполнится rm -rf.

2023-07-27 08:51 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +* [Практическое руководство  «Делай как я»](./gbt_liquibase.ru.md) <i class="fa fa-arrow-left" aria-hidden="true"></i>
gbt_liquibase.ru.md - я не уверена, что данная ссылка подходит под описание [Практическое руководство  «Делай как я»].

2023-07-27 08:52 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
Где-то в тексте данного файла нужно сослаться на gbt_liquibase.ru.md.

2023-07-27 17:11 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +  - Нажите `"Скачать fdg файл"`. Данный файл будет иметь название `GenConfig.fdg`, в нём появится опция `"LiquibaseSQL": true` в разделе, который соответствует выбранной СУБД (в данном примере - `Pos
Хотелось бы исправить стилистику в текущей версии, но не возвращать старую. Я стараюсь придерживаться краткости. На мой взгляд, в оригинальной статье приличное место занимают вводные и связующие фразы, и текст, напрямую не относящийся к сути (например "При обновлении диаграмм в дизайнере (добавление новых, изменение сущствующих классов) необходимо также изменить и структуру существующей базы данных. Для этого в технологии есть возможность сгенерировать как полноценные SQL-скрипты для всей БД, так и SQL-скрипты для обновления схемы с помощью `liquibase`" - про liquibase здесь только в конце сказано; про генерацию можно почитать в другой статье).

2023-07-31 10:08 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +```yaml
Добавил

2023-07-31 10:08 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +Чтобы запускать команды Liquibase в Azure Pipelines, необходимо иметь агента сборки с установленным Liquibase CLI. Если такого агента у вас нет, есть альтернативное решение. В момент сборки скрипты н
Объяснил, что CLI устанавливается вместе с Liquibase. (Хотя сам Liquibase это и есть CLI)

2023-07-31 10:10 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> -Большинство приложений разрабатывается командой из нескольких человек и имеет несколько стендов. Например, стенд разработки, пре-прод и прод. В связи с этим встаёт вопрос о безопасной и бесконфликтно
Похоже на введение к курсовой. Предлагаю сократить: "Использование Liquibase в вашем проекте облегчает развертывание скриптов на нескольких серверах".

2023-07-31 10:18 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +### Создание скриптов
Исправлены замечания (во всей статье).

2023-07-31 10:18 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
Пересмотрел старую статью. Добавил абзац про changelog. В остальном, мне показалось, что всё хорошо. Или есть предложения?

2023-07-31 10:19 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +* [Практическое руководство  «Делай как я»](./gbt_liquibase.ru.md) <i class="fa fa-arrow-left" aria-hidden="true"></i>
Подпись исправил

2023-07-31 10:19 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
Сослался

2023-07-31 12:19 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +  - Нажите `"Скачать fdg файл"`. Данный файл будет иметь название `GenConfig.fdg`, в нём появится опция `"LiquibaseSQL": true` в разделе, который соответствует выбранной СУБД (в данном примере - `Pos
На мой взгляд, некоторая "не краткость" зачастую позволяет свести в единую систему знания по вопросам. В исходном варианте сразу видно место ликвибейза в нашей системе.

2023-07-31 12:19 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> -Большинство приложений разрабатывается командой из нескольких человек и имеет несколько стендов. Например, стенд разработки, пре-прод и прод. В связи с этим встаёт вопрос о безопасной и бесконфликтно
Ну, вот мне, как человеку, не работавшему с ликвибейз, было бы полезно такое введение в тему.

2023-07-31 12:24 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
Можно поиском по тексту найти как минимум упоминание "ваш" и переделать на обезличенную форму. Сейчас таких упоминаний значительное количество.

2023-07-31 12:25 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
Комментарии Анастасии уже исправил

2023-07-31 12:39 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +1. Инициализировать Liquibase в корневой папке вашего проекта: `liquibase init project` (следовать инструкциям на экране). При создании проекта, требуется указать адрес БД в формате JDBC URL, и данны
Лишние запятые в "При создании проекта требуется указать адрес БД в формате JDBC URL и данные для подключения (логин и пароль).".

Ещё неплохо бы было пример адреса в нужном формате, чтобы легче было ориентироваться.

2023-07-31 12:47 UTC, Nasutya requested changes

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Использование Liquibase в вашем проекте позволяет отслеживать изменения схем БД, откатывать (rollback) базы до нужного состояния, облегчает развертывание скриптов на разных серверах.
Опять личностное обращение

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Liquibase позволяет запускать команды через свой CLI. В качестве альтернативы, можно запускать CLI в виде Docker контейнера.
Лучше свой заменить на собственный

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +1. Инициализировать Liquibase в корневой папке вашего проекта: `liquibase init project` (следовать инструкциям на экране). При создании проекта, требуется указать адрес БД в формате JDBC URL, и данны
И тут опять вашего

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +  > Подробнее в [практическом руководстве по созданию приложения с помощью Flexberry Designer Enterprise](../../practical-guides/flexberry-designer-enterprise/gpg_practical-guide.md)
я бы оставила ссылку только на "практическом руководстве"

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Есть возможность написать скрипт самостоятельно. Для этого необходимо в начало вашего обычного `.sql` скрипта добавить следующие строчки:
Опять вашего

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +> [Ссылка на полный список команд](https://docs.liquibase.com/commands/home.html)
Лучше просто "Полный список команд"

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Liquibase позволяет откатывать изменения. Это можно сделать с помощью команд `rollback`, `rollback-to-date`, `rollback-count` (см. [rollback](https://docs.liquibase.com/commands/home.html#database-ro
Я бы сделала команды списком, так нагляднее

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Вашему приложению может потребоваться использовать несколько баз данных, и развёртывать скрипты на разных БД (или разных схемах одной БД). Для этого можно воспользоваться контекстами в Liquibase.
Снова вашему

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +*Контекст* - это группа, в которую помещаются changelog'и для того, чтобы фильтровать скрипты по контексту и применять только нужные вам изменения ([подробнее](https://docs.liquibase.com/concepts/cha
Вам

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Чтобы отнести файл/папку к контексту, добавьте параметр `contextFilter` в ваш changelog:
Добавьте, ваш

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +> **Пример.** Представим - приложение имеет 2 БД - основную и `storm` (для хранения полномочий и настроек). Чтобы применять скрипты на двух базах, необходимо добавить 2 папки: `/SQL/app` - для скрипт
Представим

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +> Чтобы упростить жизнь разработчиков, можно написать `cmd` или `sh` скрипт, который будет подставлять нужный url БД в зависимости от переданного контекста. Вызывать его, например, так: `./liquibase.
Упростить жизнь - лучше перефразировать

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +Чтобы запускать команды Liquibase в Azure Pipelines, необходимо иметь агента сборки с установленным Liquibase CLI. Если такого агента у вас нет, есть альтернативное решение. В момент сборки скрипты н
Вас, используйте

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +    # отбираем только файлы скриптов:
Если не вставка из кода - переформулировать отбираем и тп

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +> Будьте осторожны! В данном скрипте переменная `WorkingDirectory` обязательно должна иметь значение (не забудьте скопировать variables!). В противном случае на шаге "Очистка папок" будет запущена ко
Внимание! либо Важно!
Не забудьте

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +Для работы представленного пайплайна, не забудьте добавить `sshEndpoint` в настройках проекта (задать данные для подключения к удалённому серверу, на котором будет запускаться liquibase), а также зад
Не забудьте, вы хотите

2023-07-31 12:47 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +В `variables` вы можете изменить команду запуска liquibase на следующие:
Вы можете

2023-08-08 12:41 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Использование Liquibase в вашем проекте позволяет отслеживать изменения схем БД, откатывать (rollback) их до нужного состояния, облегчает развертывание скриптов на разных серверах.
Исправлено

2023-08-08 12:41 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +1. Инициализируйте Liquibase в корневой папке вашего проекта: `liquibase init project` (следуйте инструкциям на экране). При создании проекта, вам нужно будет указать адрес БД в формате JDBC URL, и д
Исправлено

2023-08-08 12:41 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +> Настройки сохраняются в файл `liquibase.properties`. Настройки применяются по умолчанию. Вы можете использовать этот файл, чтобы изменить подключение или схему, на которой будут запущены скрипты. Б
Исправлено

2023-08-08 12:42 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +#### Рекомендации
Исправлено

2023-08-08 12:42 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +1. Инициализировать Liquibase в корневой папке вашего проекта: `liquibase init project` (следовать инструкциям на экране). При создании проекта, требуется указать адрес БД в формате JDBC URL, и данны
Исправлено

2023-08-08 12:42 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Использование Liquibase в вашем проекте позволяет отслеживать изменения схем БД, откатывать (rollback) базы до нужного состояния, облегчает развертывание скриптов на разных серверах.
Исправлено

2023-08-08 12:43 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Liquibase позволяет запускать команды через свой CLI. В качестве альтернативы, можно запускать CLI в виде Docker контейнера.
Исправлено

2023-08-08 12:43 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +1. Инициализировать Liquibase в корневой папке вашего проекта: `liquibase init project` (следовать инструкциям на экране). При создании проекта, требуется указать адрес БД в формате JDBC URL, и данны
Исправлено

2023-08-08 12:43 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Есть возможность написать скрипт самостоятельно. Для этого необходимо в начало вашего обычного `.sql` скрипта добавить следующие строчки:
Исправлено

2023-08-08 12:43 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +  > Подробнее в [практическом руководстве по созданию приложения с помощью Flexberry Designer Enterprise](../../practical-guides/flexberry-designer-enterprise/gpg_practical-guide.md)
Исправлено

2023-08-08 12:43 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +> [Ссылка на полный список команд](https://docs.liquibase.com/commands/home.html)
Исправлено

2023-08-08 12:43 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Liquibase позволяет откатывать изменения. Это можно сделать с помощью команд `rollback`, `rollback-to-date`, `rollback-count` (см. [rollback](https://docs.liquibase.com/commands/home.html#database-ro
Исправлено

2023-08-08 12:44 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Вашему приложению может потребоваться использовать несколько баз данных, и развёртывать скрипты на разных БД (или разных схемах одной БД). Для этого можно воспользоваться контекстами в Liquibase.
Исправлено

2023-08-08 12:44 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +*Контекст* - это группа, в которую помещаются changelog'и для того, чтобы фильтровать скрипты по контексту и применять только нужные вам изменения ([подробнее](https://docs.liquibase.com/concepts/cha
Исправлено

2023-08-08 12:44 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +> **Пример.** Представим - приложение имеет 2 БД - основную и `storm` (для хранения полномочий и настроек). Чтобы применять скрипты на двух базах, необходимо добавить 2 папки: `/SQL/app` - для скрипт
Исправлено

2023-08-08 12:44 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +Чтобы запускать команды Liquibase в Azure Pipelines, необходимо иметь агента сборки с установленным Liquibase CLI. Если такого агента у вас нет, есть альтернативное решение. В момент сборки скрипты н
Исправлено

2023-08-08 12:45 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +В `variables` вы можете изменить команду запуска liquibase на следующие:
Исправлено

2023-08-09 04:30 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +   - `liquibase changelog-sync` отметит существующие скрипты в папках как "применённые", сохранив информацию о них в таблицу `databasechangelog`; - после этого командой `update` будут применяться тол
"`databasechangelog`;" - тут точка с запятой нужны или опечатка?

2023-08-09 05:12 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +- [Использование Liquibase в Docker](https://docs.liquibase.com/workflows/liquibase-community/using-liquibase-and-docker.html)
Для единообразия стиля списка стоит тогда писать "Использовать Liquibase в Docker".

2023-08-09 05:16 UTC, bratchikov commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +2. [Online версия](https://flexberry.github.io/ru/fdo_landing_page.html)
```suggestion
2. [Flexberry Designer Enterprise](https://flexberry.github.io/ru/gpg_practical-guide.html)
```

2023-08-09 05:16 UTC, bratchikov commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +> Команды необходимо запускать из папки, в которой был инициализирован liquibase (корневая папка).
Посмотри какую структуру приложения по умолчанию создаёт генератор приложений. Там под SQL для Postgres отдельная папка. Файлы liquibase где-то там рядом должны быть, а не в корне.

2023-08-09 05:16 UTC, bratchikov commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Liquibase - это библиотека с открытым исходным кодом для отслеживания, управления и применения изменений схемы базы данных. Является аналогом Git для баз данных. Вместо "коммитов" - changesets, предс
```suggestion
Liquibase - это библиотека с открытым исходным кодом для отслеживания, управления и применения изменений схемы базы данных. Является аналогом Git для баз данных. Вместо "коммитов" - changesets, представляющие наборы SQL DDL команд на изменение схем БД.
```

2023-08-09 05:16 UTC, bratchikov commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +**Важно!** "Из коробки" откат изменений работать не будет. Для каждого скрипта необходимо указывать команды для отката (см. [rollback actions](https://docs.liquibase.com/concepts/changelogs/sql-forma
```suggestion
**Важно!** "Из коробки" откат изменений работать не будет. Для каждого скрипта необходимо указывать команды для отката (см. [rollback actions](https://docs.liquibase.com/concepts/changelogs/sql-format.html#rollback-actions)). Flexberry Designer не генерирует таких команд.
```

2023-08-09 05:21 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +1. Указать название схемы `liquibase` для хранения внутренних таблиц Liquibase. В файл `liquibase.properties` добавить строчку:
А где-то уже была информация, что это за файл `liquibase.properties` и где он лежит?

2023-08-09 05:43 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +Liquibase - это библиотека с открытым исходным кодом для отслеживания, управления и применения изменений схемы базы данных. Является аналогом Git для баз данных. Вместо "коммитов" - changesets, предс
Liquibase позволяет делать не только DDL [ссылка](https://docs.liquibase.com/change-types/home.html), но и DML - см. Data.

2023-08-09 05:57 UTC, Nasutya requested changes

2023-08-09 05:57 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +> Если в контейнере папка `/liquibase/changelog/` становится пустой, возможно вы запускаете команду из Windows через Git Bash. В таком случае, перед запуском задайте ENV переменную
Вы, задайте

2023-08-09 05:57 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +*Контекст* - это группа, в которую помещаются changelog'и для того, чтобы фильтровать скрипты по контексту и применять только нужные изменения ([подробнее](https://docs.liquibase.com/concepts/changel
Changelog/changelogs

2023-08-09 05:57 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +> **Пример.** Приложение имеет 2 БД - основную и `storm` (для хранения полномочий и настроек). Чтобы применять скрипты на двух базах, необходимо добавить 2 папки: `/SQL/app` - для скриптов основного
Я бы шаги сделала списком

2023-08-09 05:58 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +1. Указать название схемы `liquibase` для хранения внутренних таблиц Liquibase. В файл `liquibase.properties` добавить строчку:
Да, строка 27

2023-08-09 06:00 UTC, Nasutya requested changes

2023-08-09 06:00 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +- `--search-path=/liquibase/changelog/` - путь, в котором будет производиться поиск changelog'ов
Changelog/changelogs

2023-08-09 06:04 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +- `--changeset author:id` - где `author` - автор изменений, `id` - уникальный идентификатор набора изменений _(рекомендуется использовать текущую дату и время)_.
Добавь, пожалуйста, пример такого скрипта с 2-3 changeset, чтобы сразу понятно было со структурой.

2023-08-09 06:07 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +   - `liquibase changelog-sync` отметит существующие скрипты в папках как "применённые", сохранив информацию о них в таблицу `databasechangelog`; - после этого командой `update` будут применяться тол
Исправил. Убрал тире, точка с запятой нужна.

2023-08-09 06:09 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +**MSYS_NO_PATHCONV=1**
Стоит сразу добавить команду, как задавать эту переменную в git bash.

2023-08-09 06:10 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +**Важно!** "Из коробки" откат изменений работать не будет. Для каждого скрипта необходимо указывать команды для отката (см. [rollback actions](https://docs.liquibase.com/concepts/changelogs/sql-forma
Можно оформить это как заметку с уровнем important (не помню точно синтаксис).

2023-08-09 06:11 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +В приложении может потребоваться использовать несколько баз данных, и развёртывать скрипты на разных БД (или разных схемах одной БД). Для этого можно воспользоваться контекстами в Liquibase.
"баз данных, и развёртывать " - вроде запятая лишняя.

2023-08-09 06:21 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +> **Пример.** Приложение имеет 2 БД - основную и `storm` (для хранения полномочий и настроек). Чтобы применять скрипты на двух базах, необходимо добавить 2 папки: `/SQL/app` - для скриптов основного
+1

2023-08-09 06:23 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +> Чтобы облегчить процесс обновления, можно написать `cmd` или `sh` скрипт, который будет подставлять нужный url БД в зависимости от переданного контекста. Вызывать его, например, так: `./liquibase.s
Предлагаю скрипт https://gist.github.com/turbcool/969c545421cc0d8b43fa8b8c391e6571 перенести куда-то в файлы на flexberry.github.io.

2023-08-09 06:31 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +- задать переменную `liquibaseContext` для конвеера если конвеер будет запущен на каком-либо контексте
" для конвеера, если конвеер" - нужна запятая

2023-08-09 06:33 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +Liquibase записывает часть действий в stderr (лог ошибок). Для того, чтобы успешный запуск Liquibase не возвращал ошибку в Azure Pipelines, необходимо добавить опцию `failOnStdErr: false` (см. шаг "З
А как в итоге решена проблема, что может туда реальная ошибка выпасть и оно не упадёт?

2023-08-09 07:49 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +Liquibase записывает часть действий в stderr (лог ошибок). Для того, чтобы успешный запуск Liquibase не возвращал ошибку в Azure Pipelines, необходимо добавить опцию `failOnStdErr: false` (см. шаг "З
Пояснил этот момент.

2023-08-09 07:50 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase_azure.ru.md
> +- задать переменную `liquibaseContext` для конвеера если конвеер будет запущен на каком-либо контексте
Исправлено

2023-08-09 07:55 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +**MSYS_NO_PATHCONV=1**
Пояснил

2023-08-09 07:55 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +- `--changeset author:id` - где `author` - автор изменений, `id` - уникальный идентификатор набора изменений _(рекомендуется использовать текущую дату и время)_.
Добавил пример

2023-08-09 07:55 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +> **Пример.** Приложение имеет 2 БД - основную и `storm` (для хранения полномочий и настроек). Чтобы применять скрипты на двух базах, необходимо добавить 2 папки: `/SQL/app` - для скриптов основного
Исправлено

2023-08-09 07:55 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +*Контекст* - это группа, в которую помещаются changelog'и для того, чтобы фильтровать скрипты по контексту и применять только нужные изменения ([подробнее](https://docs.liquibase.com/concepts/changel
Исправлено

2023-08-09 07:55 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +> Если в контейнере папка `/liquibase/changelog/` становится пустой, возможно вы запускаете команду из Windows через Git Bash. В таком случае, перед запуском задайте ENV переменную
Исправлено

2023-08-09 07:56 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +**Важно!** "Из коробки" откат изменений работать не будет. Для каждого скрипта необходимо указывать команды для отката (см. [rollback actions](https://docs.liquibase.com/concepts/changelogs/sql-forma
Исправлено

2023-08-09 07:56 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +- [Использование Liquibase в Docker](https://docs.liquibase.com/workflows/liquibase-community/using-liquibase-and-docker.html)
Исправлено

2023-08-09 07:56 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +2. [Online версия](https://flexberry.github.io/ru/fdo_landing_page.html)
Исправлено

2023-08-09 08:02 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +**Важно!** "Из коробки" откат изменений работать не будет. Для каждого скрипта необходимо указывать команды для отката (см. [rollback actions](https://docs.liquibase.com/concepts/changelogs/sql-forma
Сделано

2023-08-09 10:03 UTC, Nasutya approved these changes

2023-08-09 11:29 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +> Команды необходимо запускать из папки, в которой был инициализирован liquibase (корневая папка).
Да, они генерируются в папку /SQL. В общем-то, у пользователя есть выбор где инициализировать Liquibase. Я в начале статьи рекомендовал инициализировать в корневой папке, мне кажется, это удобнее. Могу добавить вариант /SQL, или сказать, что "на ваш выбор".

2023-08-09 12:01 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_liquibase.ru.md
> +> Чтобы облегчить процесс обновления, можно написать `cmd` или `sh` скрипт, который будет подставлять нужный url БД в зависимости от переданного контекста. Вызывать его, например, так: `./liquibase.s
Вставил как код

2023-08-09 13:29 UTC, Anisimova2020 approved these changes

2023-08-09 13:31 UTC, merged