Add custom of tags in flexberry-multiple-lookup
Flexberry/flexberry.github.io pull request #189
Opened 2023-08-10 17:21 UTC by neroslovegor

2023-08-11 06:22 UTC, torres6093 commented on pages/products/flexberry-ember/3.x/components/ef3_flexberry-multiple-lookup.ru.md
> +Чтобы кастомизировать теги, необходимо в объект `tagConfig` указать параментры настройки для нужной записи. Возможные настройки:
Опечатка "параментры"

2023-08-11 07:44 UTC, TeterinaSvetlana requested changes

2023-08-11 07:44 UTC, TeterinaSvetlana commented on pages/products/flexberry-ember/3.x/components/ef3_flexberry-multiple-lookup.ru.md
> +Flexberry multiple lookup представляет собой элемент управления (компонент), позволяющий выбрать несколько значений мастера. Данный компонент является дополнением к компоненту [Flexberry lookup]().
[Flexberry lookup]() - в скобочках должна быть ссылка куда-нибудь

2023-08-11 07:53 UTC, neroslovegor commented on pages/products/flexberry-ember/3.x/components/ef3_flexberry-multiple-lookup.ru.md
> +Flexberry multiple lookup представляет собой элемент управления (компонент), позволяющий выбрать несколько значений мастера. Данный компонент является дополнением к компоненту [Flexberry lookup]().
Да, но пока для 3 версии нет статьи Flexberry lookup

2023-08-11 09:49 UTC, TeterinaSvetlana commented on pages/products/flexberry-ember/3.x/components/ef3_flexberry-multiple-lookup.ru.md
> +Flexberry multiple lookup представляет собой элемент управления (компонент), позволяющий выбрать несколько значений мастера. Данный компонент является дополнением к компоненту [Flexberry lookup]().
можно на вторую версию пока наверное

2023-11-10 11:13 UTC, Nasutya commented on pages/products/flexberry-ember/3.x/components/ef3_flexberry-multiple-lookup.ru.md
> +Flexberry multiple lookup представляет собой элемент управления (компонент), позволяющий выбрать несколько значений мастера. Данный компонент является дополнением к компоненту [Flexberry lookup]().
Если статьи нет - создать пустую и задачу на ее описание. Либо убрать пока ссылку и создать ишью на ее вставку после появления статьи
Flexberry-lookup

2023-11-10 11:13 UTC, Nasutya commented on pages/products/flexberry-ember/3.x/components/ef3_flexberry-multiple-lookup.ru.md
> +Доступно с версии ember-flexberry 3.10.0.
Про версии не надо упоминать

2023-11-10 11:13 UTC, Nasutya commented on pages/products/flexberry-ember/3.x/components/ef3_flexberry-multiple-lookup.ru.md
> +![](/images/pages/products/flexberry-ember/3.x/components/flexberry-multiply-lookup-tag-customization-example.png)
Картинкам давать наименование, хоть example, но вставить в []

2023-11-10 11:13 UTC, Nasutya commented on pages/products/flexberry-ember/3.x/components/ef3_flexberry-multiple-lookup.ru.md
> +Вы можете посмотреть [пример с реализацией](http://flexberry.github.io/ember-flexberry/dummy/dummy-test-2/?#/components-examples/flexberry-multiple-lookup/configurate-tags) на тестовом стенде.
Без Вы можете посмотреть
Пример реализации расположен там-то

2023-11-10 11:13 UTC, Nasutya commented on pages/products/flexberry-ember/3.x/components/ef3_flexberry-multiple-lookup.ru.md
> +Чтобы кастомизировать теги, необходимо в объект `tagConfig` указать параметры настройки для нужной записи. Возможные настройки:
Для кастомизации...

2023-12-05 03:39 UTC, merged