Документация по PgBouncer
Flexberry/flexberry.github.io pull request #197
Opened 2023-10-06 09:33 UTC by turbcool

2023-10-06 10:21 UTC, Anisimova2020 commented
К любому ПР желательно писать комментарий.
Например, в комментарии можно было б указать, что документация пишется на основании опыта построения стенда и указать ссылку на него.

2023-10-06 10:29 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
> +PgBouncer - это сервис, обеспечивающий `connection pooling` к экземпляру PostgreSQL. PgBouncer работает как посредник между приложением и базой данных, "транслируя" запросы к нужной БД в экземпляре и
Вероятно тут сразу можно ссылку на PgBouncer.
И в данном разделе описать, что речь пойдёт, как в типичном flexberry приложении (бэкенд на ODataService и эмбер фронтендом) добавить и настроить PgBouncer.

2023-10-06 10:31 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
> +Рекомендуется использовать образ [edoburu/pgbouncer](https://hub.docker.com/r/edoburu/pgbouncer). Для работы образа, необходимо поместить в образ файлы `/etc/pgbouncer/pgbouncer.ini` и `/etc/pgbounce
"Это можно сделать с помощью docker volumes или создав собственный Dockerfile." - может сразу ссылку на документацию добавить, как это делать?

2023-10-06 10:35 UTC, Anisimova2020 commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
> +PgBouncer - это сервис, обеспечивающий `connection pooling` к экземпляру PostgreSQL. PgBouncer работает как посредник между приложением и базой данных, "транслируя" запросы к нужной БД в экземпляре и
В статью добавить больше про то, как именно с нашей flexberry-моделью это использовать. Пока это просто на типичную инструкцию по баунсеру похоже.

2023-10-11 08:40 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
> +PgBouncer - это сервис, обеспечивающий `connection pooling` к экземпляру PostgreSQL. PgBouncer работает как посредник между приложением и базой данных, "транслируя" запросы к нужной БД в экземпляре и
Настройки для flexberry типичны. У нас разве что есть несколько БД. В статье рассматривается такой пример. Добавил в статью про Flexberry.

2023-10-11 08:49 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
> +Рекомендуется использовать образ [edoburu/pgbouncer](https://hub.docker.com/r/edoburu/pgbouncer). Для работы образа, необходимо поместить в образ файлы `/etc/pgbouncer/pgbouncer.ini` и `/etc/pgbounce
Добавил

2023-10-11 12:12 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
> +PgBouncer - это сервис, обеспечивающий `connection pooling` к экземпляру PostgreSQL. PgBouncer работает как посредник между приложением и базой данных, "транслируя" запросы к нужной БД в экземпляре и
Добавил ещё пару слов о Flexberry

2023-10-12 10:52 UTC, Nasutya requested changes

2023-10-12 10:52 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
> +[PgBouncer](https://www.pgbouncer.org) - это сервис, обеспечивающий `connection pooling` к экземпляру PostgreSQL. PgBouncer работает как посредник между приложением и базой данных, "транслируя" запро
Flexberry-приложения

2023-10-12 10:52 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
>  Рекомендуется использовать образ [edoburu/pgbouncer](https://hub.docker.com/r/edoburu/pgbouncer). Для работы образа, необходимо поместить в образ файлы `/etc/pgbouncer/pgbouncer.ini` и `/etc/pgbounce
Для работы образа (,) - запятая не нужна

2023-10-12 10:52 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
> +Настройка PgBouncer осуществляется с помощью файла конфигурации `pgbouncer.ini`. Типичное Flexberry приложение включает в себя БД приложения и БД полномочий, поэтому в файле конфигурации в разделе [d
Flexberry-приложение
[databases] - точно квадратные скобки?

2023-10-12 10:52 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
> +> Есть возможность синхронизировать пользователей PgBouncer с пользователями БД - см. параметры `auth_file`, `auth_user`, `auth_query` в [документации](https://www.pgbouncer.org/config.html#authentic
`userlist.txt` - после запятая или точка. Не тире

2023-10-12 10:52 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
>  - [`pool_mode`](https://www.pgbouncer.org/features.html) - позволяет задать режим выделения пулов:
пустая строка после :

2023-10-12 10:52 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
>  Прочие полезные настройки:
Аналогично

2023-10-12 10:52 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
> -Чтобы подключить приложение к PgBouncer, необходимо изменить строки подключения сервисов данных. Строки подключения по умолчанию задаются в файле `App.config` в проекте `ODataBackend` вашего бекенда.
Пустая строка после заголовка

2023-10-12 10:52 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
>  - [Пример использования PgBouncer в приложении Flexberry](https://github.com/Flexberry/Flexberry.PgBouncer.Sample)
Аналогично

2023-10-12 10:52 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
> -[PgBouncer](https://www.pgbouncer.org) - это сервис, обеспечивающий `connection pooling` к экземпляру PostgreSQL. PgBouncer работает как посредник между приложением и базой данных, "транслируя" запро
Пустая строка после заголовка

2023-10-12 12:21 UTC, turbcool commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
> +Настройка PgBouncer осуществляется с помощью файла конфигурации `pgbouncer.ini`. Типичное Flexberry приложение включает в себя БД приложения и БД полномочий, поэтому в файле конфигурации в разделе [d
Да, забыл включить в кавычки.

2023-10-13 05:22 UTC, Anisimova2020 approved these changes

2023-10-13 09:37 UTC, Nasutya requested changes

2023-10-13 09:37 UTC, Nasutya commented on pages/guides/base-tech/storage/gbt_pgbouncer.ru.md
> +Настройка PgBouncer осуществляется с помощью файла конфигурации `pgbouncer.ini`. Типичное Flexberry приложение включает в себя БД приложения и БД полномочий, поэтому в файле конфигурации в разделе `[
Здесь нет дефиса. Лучше прогонять через поиск.

2023-10-13 11:46 UTC, Nasutya approved these changes

2023-10-16 03:14 UTC, merged